application: drssgenerator
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: Main.app
  secure: optional

- url: /frequenthub
  script: cron.app
  #login: admin
  
#- url: /rss.xml
 # script: test.app
  #secure: optional